name: main

on:
  push:
    branches: [main]
  pull_request:

env:
  TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
  TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
  TEST_GUILD_ID: ${{ secrets.TEST_GUILD_ID }}

jobs:
  run-scripts:
    strategy:
      matrix:
        scripts:
          - name: test
            script: test --parallel
          - name: lint
            script: lint
          - name: typecheck
            script: typecheck
          - name: build
            script: build
      fail-fast: false
    name: ${{ matrix.scripts.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # https://github.com/actions/setup-node#supported-version-syntax
          node-version: "16"
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run --recursive ${{ matrix.scripts.script }}
